enum ResponseStatus {
  "UNKNOWN_ERROR" = 1,
  "BAD_REQUEST" = 400,
  "NOT_AUTHORIZED" = 401,
  "INTERNAL_SERVER_ERROR" = 500,
  "UNHANDLED_REJECTION" = 503,
}

enum Routes {
  MAIN = "/",
  PRODUCTS = "/products",
  CATEGORIES = "/categories",
  ABOUT = "/about",
}

const DEFAULT_ERROR_STATUS = 0;
const DEFAULT_PRODUCT_ID = -1;
const DEFAULT_CATEGORY_ID = -1;
const DEFAULT_PRODUCTS_OFFSET = 0;
const DEFAULT_PRODUCTS_LIMIT = 9;
const DEFAULT_MAX_PRODUCTS_LIMIT = 10000;
const INIT_PRODUCTS_COUNT = 0;

export {
  ResponseStatus,
  Routes,
  DEFAULT_ERROR_STATUS,
  DEFAULT_PRODUCT_ID,
  DEFAULT_CATEGORY_ID,
  DEFAULT_PRODUCTS_OFFSET,
  DEFAULT_PRODUCTS_LIMIT,
  DEFAULT_MAX_PRODUCTS_LIMIT,
  INIT_PRODUCTS_COUNT,
};
